version: 2
jobs:
  build_frontend:
    docker:
      - image: circleci/node:8
    working_directory: ~/frontend
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "frontend/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: 
          name: Install Packages
          command: cd frontend && npm install

      - save_cache:
          paths:
            - frontend/node_modules
          key: v1-dependencies-{{ checksum "frontend/package.json" }}
        
      - run: 
          name: Build Frontend
          command: cd frontend && yarn run build
  
  build_backend:
    docker:
      - image: circleci/node:8
    working_directory: ~/backend
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "backend/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: 
          name: Install Package
          command: cd backend && npm install

      - save_cache:
          paths:
            - backend/node_modules
          key: v1-dependencies-{{ checksum "backend/package.json" }}

workflows:
  version: 2
  workflow:
    jobs:
      - build_frontend
      - build_backend

deployment:
  staging:
    branch: master
    heroku:
      appname: shopyyy