version: 2
jobs:
  build-frontend:
    docker:
      - image: circleci/node:8
    working_directory: ~/frontend
    steps:
      - checkout

workflows:
  version: 2
  workflow:
    jobs:
      - build-frontend